In [1]:
import numpy as np

In [87]:
x1 = np.array([1, 0, 1, 0]) # Входы
x2 = np.array([1, 1, 0, 0])
x3 = np.array([1, 1, 1, 0])
x4 = np.array([1, 0, 1, 1])

In [88]:
w1 = np.array([4, -1 , 0, -1]) # Веса
w2 = np.array([0, -10 , 5, 2])
w3 = np.array([5, 0 , -1, -5])
w4 = np.array([-5, -1 , 5, 0])

In [89]:
list_enters = [x1, x2, x3, x4]
list_wight = [w1, w2, w3, w4]

In [90]:
for i in range(len(w1)):
    answer = np.dot(list_wight[i].T, list_enters[i])
    if answer > 0:
        print('YES', answer)
    else:
        print('No', answer)

YES 4
No -10
YES 4
No 0


In [25]:
wT

array([ 5,  0, -1, -5])

In [26]:
w

array([ 5,  0, -1, -5])

Определение логической функции

In [103]:
#Веса
w = np.array([-1.5, 1, 1])
# входы
x = np.array([1, 0, 0])

In [104]:
print(np.dot(w.T, x))

-1.5


### Обучение перцептрона 

Обучение перцептрона на некоторых данных различать груши и не груши (пока не надо обучать до сходимости: просто примеяем обучающее правило последовательно по одному разу на каждом примере, всего должно получится 3 последовательных применения обучающего правила). 

Пусть у нас есть перцептрон с весами (0, 0) и смещением 0. 

In [201]:
W = np.array([0., 0., 0.])

Далее определяем входы в следующем порядке: фиктивный, желтизна, семитричность.

In [202]:
X = np.array([1., 1., 0.3]) # Данные входы должны дать 1, т.е это груша

In [203]:
# Корректный ответ
y = 1

In [204]:
base = np.dot(W.T, X)
print(base)
if base > W[0]:
    e = 1
else:
    e = 0

if e != y:
    if e == 0:
        W[0] = W[0]  + X[0]
        W[1] = W[1]  + X[1]
        W[2] = W[2]  + X[2]
    if e == 1:
        W[0] = W[0]  - X[0]
        W[1] = W[1]  - X[1]
        W[2] = W[2]  - X[2]

0.0


In [205]:
W

array([ 1. ,  1. ,  0.3])

С получившимися весами, переходим к следующей проверке на входы

In [206]:
X = np.array([1., 0.4, 0.5]) # Данные входы должны дать 1, т.е это груша

In [207]:
# Корректный ответ
y = 1

In [208]:
base = np.dot(W.T, X)
print(base)
if base > W[0]:
    e = 1
else:
    e = 0

if e != y:
    if e == 0:
        W[0] = W[0]  + X[0]
        W[1] = W[1]  + X[1]
        W[2] = W[2]  + X[2]
    if e == 1:
        W[0] = W[0]  - X[0]
        W[1] = W[1]  - X[1]
        W[2] = W[2]  - X[2]

1.55


In [209]:
W

array([ 1. ,  1. ,  0.3])

С получившимися весами, переходим к следующей проверке на входы

In [210]:
X = np.array([1., 0.7, 0.8]) # Данные входы должны дать 0, т.е это не груша

In [211]:
# Корректный ответ
y = 0

In [212]:
base = np.dot(W.T, X)
print(base)
if base > W[0]:
    e = 1
else:
    e = 0

if e != y:
    if e == 0:
        W[0] = W[0]  + X[0]
        W[1] = W[1]  + X[1]
        W[2] = W[2]  + X[2]
    if e == 1:
        W[0] = W[0]  - X[0]
        W[1] = W[1]  - X[1]
        W[2] = W[2]  - X[2]

1.94


In [213]:
W

array([ 0. ,  0.3, -0.5])

Вывод в виде:смещение, вес для желтизны фрукта и вес для его симметричности